// PLACEHOLDER LEGAL CONTENT — must be reviewed and approved by a licensed
// attorney before this page goes live in production.

import type { ReactNode } from "react";

const SECTIONS = [
  { id: "introduction", title: "1. Introduction" },
  { id: "definitions", title: "2. Definitions" },
  { id: "information-collection-and-use", title: "3. Information Collection and Use" },
  { id: "types-of-data-collected", title: "4. Types of Data Collected" },
  { id: "use-of-data", title: "5. Use of Data" },
  { id: "retention-of-data", title: "6. Retention of Data" },
  { id: "transfer-of-data", title: "7. Transfer of Data" },
  { id: "disclosure-of-data", title: "8. Disclosure of Data" },
  { id: "security-of-data", title: "9. Security of Data" },
  { id: "gdpr", title: "10. Your Rights Under GDPR" },
  { id: "calOppa", title: "11. Your Rights Under CalOPPA" },
  { id: "ccpa", title: "12. Your Rights Under CCPA" },
  { id: "service-providers", title: "13. Service Providers" },
  { id: "analytics", title: "14. Analytics" },
  { id: "links-to-other-sites", title: "15. Links to Other Sites" },
  { id: "childrens-privacy", title: "16. Children's Privacy" },
  { id: "changes", title: "17. Changes to This Privacy Policy" },
  { id: "contact", title: "18. Contact Us" },
];

const DEFINITIONS = [
  {
    term: "SERVICE",
    body: "means the mvcustombuilders.com website operated by MV Custom Builders.",
  },
  {
    term: "PERSONAL DATA",
    body: "means data about a living individual who can be identified from that data.",
  },
  {
    term: "USAGE DATA",
    body: "is data collected automatically, generated by use of the Service or from the Service's infrastructure (for example, the duration of a page visit).",
  },
  {
    term: "COOKIES",
    body: "are small files stored on your device.",
  },
  {
    term: "DATA CONTROLLER",
    body: "means the entity that determines the purposes and means of processing personal data. For this Privacy Policy, MV Custom Builders is the Data Controller.",
  },
  {
    term: "DATA PROCESSORS (SERVICE PROVIDERS)",
    body: "means third parties who process data on our behalf.",
  },
];

const USE_OF_DATA = [
  "Respond to your inquiry and provide requested information about our services;",
  "Maintain and improve the Service;",
  "Monitor and analyze usage of the Service;",
  "Detect, prevent, and address technical issues;",
  "Comply with legal obligations.",
];

const DISCLOSURE_OF_DATA = [
  "If required to do so by law or in response to valid requests by public authorities;",
  "If MV Custom Builders is involved in a merger, acquisition, or asset sale;",
  "To service providers who support our business operations (e.g. our contact form and analytics providers), who are obligated not to use your data for any other purpose;",
  "With your consent, in any other case.",
];

function SectionHeading({ number, title }: { number: string; title: string }) {
  return (
    <h2 className="text-xl font-extrabold tracking-[-0.02em] text-mvcb-black uppercase">
      {number}. {title}
    </h2>
  );
}

function SubHeading({ children }: { children: ReactNode }) {
  return (
    <h3 className="mt-5 text-sm font-bold tracking-wide text-mvcb-black uppercase">
      {children}
    </h3>
  );
}

export default function PrivacyPolicyPage() {
  return (
    <>
      {/* HERO */}
      <section className="border-b border-mvcb-line py-10 md:py-16">
        <div className="mx-auto max-w-6xl px-8 sm:px-12 lg:px-16">
          <h1 className="text-3xl font-extrabold tracking-[-0.02em] uppercase text-mvcb-black md:text-4xl">
            Privacy Policy
          </h1>
          <p className="mt-2 text-sm text-muted-foreground">
            Effective date: September 19, 2026 &middot; MV Custom Builders LLC
          </p>
        </div>
      </section>

      {/* BODY */}
      <section className="py-10 md:py-16">
        <div className="mx-auto flex max-w-6xl flex-col gap-12 px-6 sm:px-8 lg:flex-row">
          <nav aria-label="Policy sections" className="shrink-0 lg:w-56">
            <span className="text-xs font-semibold tracking-wide text-mvcb-black uppercase">
              Sections
            </span>
            <ul className="mt-4 flex flex-col gap-3 text-sm">
              {SECTIONS.map((section) => (
                <li key={section.id}>
                  <a
                    href={`#${section.id}`}
                    className="text-muted-foreground hover:text-mvcb-orange"
                  >
                    {section.title}
                  </a>
                </li>
              ))}
            </ul>
          </nav>

          <div className="flex flex-1 flex-col gap-10">
            <div id="introduction">
              <SectionHeading number="1" title="Introduction" />
              <p className="mt-3 text-sm leading-relaxed text-muted-foreground">
                Welcome to MV Custom Builders.
              </p>
              <p className="mt-3 text-sm leading-relaxed text-muted-foreground">
                MV Custom Builders (&quot;us&quot;, &quot;we&quot;, or
                &quot;our&quot;) operates mvcustombuilders.com (the
                &quot;Service&quot;).
              </p>
              <p className="mt-3 text-sm leading-relaxed text-muted-foreground">
                This Privacy Policy governs your visit to
                mvcustombuilders.com and explains how we collect, safeguard,
                and disclose information that results from your use of our
                Service. We use your data to provide and improve the
                Service. By using the Service, you agree to the collection
                and use of information in accordance with this policy.
              </p>
            </div>

            <div id="definitions">
              <SectionHeading number="2" title="Definitions" />
              <ul className="mt-3 flex flex-col gap-3 text-sm leading-relaxed text-muted-foreground">
                {DEFINITIONS.map((definition) => (
                  <li key={definition.term}>
                    <span className="font-semibold text-mvcb-black">
                      {definition.term}
                    </span>{" "}
                    {definition.body}
                  </li>
                ))}
              </ul>
            </div>

            <div id="information-collection-and-use">
              <SectionHeading number="3" title="Information Collection and Use" />
              <p className="mt-3 text-sm leading-relaxed text-muted-foreground">
                We collect a limited set of information to respond to
                inquiries and improve the Service.
              </p>
            </div>

            <div id="types-of-data-collected">
              <SectionHeading number="4" title="Types of Data Collected" />

              <SubHeading>Personal Data</SubHeading>
              <p className="mt-3 text-sm leading-relaxed text-muted-foreground">
                When you submit our contact form, we collect:
              </p>
              <ul className="mt-3 flex flex-col gap-2 pl-5 text-sm leading-relaxed text-muted-foreground [&>li]:list-disc">
                <li>Name</li>
                <li>Email address</li>
                <li>Phone number</li>
                <li>Project type and any details you provide in your message</li>
              </ul>

              <SubHeading>Usage Data</SubHeading>
              <p className="mt-3 text-sm leading-relaxed text-muted-foreground">
                We automatically collect certain information when you visit
                the Service, including your IP address, browser type, pages
                visited, time and date of visit, and time spent on the site,
                via Google Analytics (GA4).
              </p>

              <SubHeading>Tracking Cookies Data</SubHeading>
              <p className="mt-3 text-sm leading-relaxed text-muted-foreground">
                We use cookies and similar tracking technologies (via Google
                Analytics) to understand how visitors use our Service. You
                can instruct your browser to refuse cookies, though some
                parts of the Service may not function as intended without
                them.
              </p>
            </div>

            <div id="use-of-data">
              <SectionHeading number="5" title="Use of Data" />
              <p className="mt-3 text-sm leading-relaxed text-muted-foreground">
                We use the data we collect to:
              </p>
              <ul className="mt-3 flex flex-col gap-2 text-sm leading-relaxed text-muted-foreground">
                {USE_OF_DATA.map((item, index) => (
                  <li key={item}>
                    5.{index + 1}. {item}
                  </li>
                ))}
              </ul>
              <p className="mt-3 text-sm leading-relaxed text-muted-foreground">
                We do not use your data for newsletters, marketing emails, or
                promotional communications unless you separately opt in.
              </p>
            </div>

            <div id="retention-of-data">
              <SectionHeading number="6" title="Retention of Data" />
              <p className="mt-3 text-sm leading-relaxed text-muted-foreground">
                We retain Personal Data only as long as necessary to respond
                to your inquiry and comply with legal obligations. Usage Data
                collected via analytics is retained according to Google
                Analytics&apos; standard retention settings.
              </p>
            </div>

            <div id="transfer-of-data">
              <SectionHeading number="7" title="Transfer of Data" />
              <p className="mt-3 text-sm leading-relaxed text-muted-foreground">
                MV Custom Builders is based in the United States, and any
                data you provide is processed and stored in the United
                States. If you are located outside the United States and
                choose to provide information to us, please note that your
                data will be transferred to and processed in the United
                States.
              </p>
            </div>

            <div id="disclosure-of-data">
              <SectionHeading number="8" title="Disclosure of Data" />
              <p className="mt-3 text-sm leading-relaxed text-muted-foreground">
                We may disclose your Personal Data:
              </p>
              <ul className="mt-3 flex flex-col gap-2 text-sm leading-relaxed text-muted-foreground">
                {DISCLOSURE_OF_DATA.map((item, index) => (
                  <li key={item}>
                    8.{index + 1}. {item}
                  </li>
                ))}
              </ul>
              <p className="mt-3 text-sm leading-relaxed text-muted-foreground">
                We do not sell your Personal Data to third parties.
              </p>
            </div>

            <div id="security-of-data">
              <SectionHeading number="9" title="Security of Data" />
              <p className="mt-3 text-sm leading-relaxed text-muted-foreground">
                We take reasonable steps to protect your data, but no method
                of transmission over the internet or electronic storage is
                100% secure, and we cannot guarantee absolute security.
              </p>
            </div>

            <div id="gdpr">
              <SectionHeading number="10" title="Your Data Protection Rights Under GDPR" />
              <p className="mt-3 text-sm leading-relaxed text-muted-foreground">
                If you are a resident of the European Union or European
                Economic Area, you have rights under GDPR, including the
                right to access, correct, delete, restrict, or port your
                data, and the right to withdraw consent. To exercise these
                rights, email us at{" "}
                <a
                  href="mailto:mvcustombuilder@gmail.com"
                  className="text-mvcb-black underline hover:text-mvcb-orange"
                >
                  mvcustombuilder@gmail.com
                </a>
                .
              </p>
            </div>

            <div id="calOppa">
              <SectionHeading number="11" title="Your Data Protection Rights Under CalOPPA" />
              <p className="mt-3 text-sm leading-relaxed text-muted-foreground">
                We agree to the following: users can visit our site
                anonymously; this Privacy Policy is linked from our
                homepage; users will be notified of policy changes on this
                page. We honor Do Not Track browser signals.
              </p>
            </div>

            <div id="ccpa">
              <SectionHeading number="12" title="Your Data Protection Rights Under CCPA" />
              <p className="mt-3 text-sm leading-relaxed text-muted-foreground">
                If you are a California resident, you may request to know
                what personal information we&apos;ve collected about you,
                request deletion of your data, and opt out of the sale of
                your data. We do not sell personal information. To exercise
                these rights, email{" "}
                <a
                  href="mailto:mvcustombuilder@gmail.com"
                  className="text-mvcb-black underline hover:text-mvcb-orange"
                >
                  mvcustombuilder@gmail.com
                </a>
                .
              </p>
            </div>

            <div id="service-providers">
              <SectionHeading number="13" title="Service Providers" />
              <p className="mt-3 text-sm leading-relaxed text-muted-foreground">
                We use third-party service providers to operate parts of our
                Service, including form submission handling and website
                analytics. These providers only access your data to perform
                their specific function and are obligated not to use it for
                any other purpose.
              </p>
            </div>

            <div id="analytics">
              <SectionHeading number="14" title="Analytics" />
              <p className="mt-3 text-sm leading-relaxed text-muted-foreground">
                We use Google Analytics (GA4) to monitor and analyze use of
                our Service. We also use Microsoft Clarity to record sessions
                and generate heatmaps of how visitors use the Service.
                Clarity masks sensitive input fields, such as form fields, by
                default.
              </p>
            </div>

            <div id="links-to-other-sites">
              <SectionHeading number="15" title="Links to Other Sites" />
              <p className="mt-3 text-sm leading-relaxed text-muted-foreground">
                Our Service may contain links to third-party sites not
                operated by us. We are not responsible for the content or
                privacy practices of any third-party sites.
              </p>
            </div>

            <div id="childrens-privacy">
              <SectionHeading number="16" title="Children's Privacy" />
              <p className="mt-3 text-sm leading-relaxed text-muted-foreground">
                Our Service is not intended for use by anyone under the age
                of 18. We do not knowingly collect personal data from
                children. If you believe a child has provided us with
                personal data, please contact us so we can remove it.
              </p>
            </div>

            <div id="changes">
              <SectionHeading number="17" title="Changes to This Privacy Policy" />
              <p className="mt-3 text-sm leading-relaxed text-muted-foreground">
                We may update this Privacy Policy from time to time. Changes
                will be posted on this page with an updated effective date.
              </p>
            </div>

            <div id="contact">
              <SectionHeading number="18" title="Contact Us" />
              <p className="mt-3 text-sm leading-relaxed text-muted-foreground">
                If you have any questions about this Privacy Policy, please
                contact us at{" "}
                <a
                  href="mailto:mvcustombuilder@gmail.com"
                  className="text-mvcb-black underline hover:text-mvcb-orange"
                >
                  mvcustombuilder@gmail.com
                </a>
                .
              </p>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}
